const providerEmoji: Record<string, string> = {
  telegram: '✈️',
  discord: '🎮',
  slack: '💬',
  whatsapp: '📱',
  signal: '📶',
  matrix: '🟢',
  imessage: '💬',
  msteams: '👥',
  mattermost: '💬',
  googlechat: '🔍',
  nostr: '🔮',
  irc: '📺',
  twitch: '🟣',
  line: '🟢',
  feishu: '🐦',
  bluebubbles: '🫧',
  tlon: '🌊',
  'nextcloud-talk': '☁️',
  'synology-chat': '💾',
  qqbot: '🐧',
  zalo: '💙',
  ollama: '🦙',
  openai: '🤖',
  anthropic: '🧠',
  google: '🔍',
  groq: '⚡',
};

export default providerEmoji;
